default_platform(:android)

import("Android")

before_all do |lane, options|
    skip_docs
    options[:conf] ||= "release"
    readAndroidParams(options)
end

desc "Runs on any branch"
lane :branch do |options|
    gradle(
        task: "assembleDebug",
        project_dir: "."
    )
end

desc "Runs on main branch"
lane :main do |options|
    gradle(
        task: "assembleDebug",
        project_dir: "."
    )
end