default_platform(:android)

import("Android")

before_all do |lane, options|
    skip_docs
    readAndroidParams(options)
end

desc "Runs on any branch"
lane :branch do |options|
    build
end

desc "Runs on main branch"
lane :main do |options|
    build
end