name: main

on:
  push:
    branches: [ main ]

env:
  CACHE_BUNDLER: ~/.bundler

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache Bundler
        uses: actions/cache@v3
        with:
          path: ${{ env.CACHE_BUNDLER }}
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install dependencies
        run: gem install bundler && bundle install

      - name: Run Fastlane main
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: main
          options: '{ "conf": "release" }'
          skip-tracking: false
          subdirectory: fastlane
          bundle-install-path: ${{ env.CACHE_BUNDLER }}